name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Qt dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            libgl1-mesa-dev \
            libglib2.0-0 \
            libxkbcommon-x11-0 \
            libxcb-xinerama0 \
            xvfb \
            sqlite3 \
            sqlcipher \
            libsqlcipher-dev

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install nox
        run: pip install nox

      - name: Run CI pipeline
        run: |
          export QT_QPA_PLATFORM=offscreen
          export DISPLAY=:99
          xvfb-run -a nox -s ci

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 30
